name: PowerShell Code Formatting

on:
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PowerShell
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser

      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          $results = Invoke-ScriptAnalyzer -Path . -Recurse -Severity Error
          if ($results) {
            Write-Host "Code formatting issues found:"
            $results | Format-Table -AutoSize
            exit 1
          }
