name: PowerShell Code Formatting

on:
  pull_request:
    branches: [main, develop]
  workflow_dispatch:  # Allows manual execution

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PowerShell
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser

      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          $results = Invoke-ScriptAnalyzer -Path . -Recurse -Severity Warning, Error
          if ($results.Count -gt 0) {
            foreach ($result in $results) {
              Write-Host "::error file=$($result.ScriptPath),line=$($result.Line)::$($result.Message)"
            }
            exit 1  # Forces the action to fail if there are formatting issues
          }
          Write-Host "No formatting issues found."
