name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract version from PowerShell script
        id: extract_version
        shell: pwsh
        run: |
          $versionLine = Get-Content -Path create.ps1 | Select-String -Pattern '^# Version: (.+)$' | ForEach-Object { $_.Matches.Groups[1].Value.Trim() }
          Write-Host "Extracted version: $versionLine"
          echo "RELEASE_TAG=$versionLine" >> "$GITHUB_ENV"

      - name: "Create release"
        env:
          RELEASE_TAG: ${{ env.RELEASE_TAG }}
      
        uses: "actions/github-script@v6"
        with:
          github-token: "${{ secrets.GHTOKEN }}"
          script: |
            const core = require('@actions/core');
      
            try {
              const releaseTag = process.env.RELEASE_TAG;
              const response = await github.rest.repos.createRelease({
                draft: false,
                generate_release_notes: true,
                tag_name: releaseTag,
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
              });
              core.exportVariable('RELEASE_ID', response.data.id);
              core.exportVariable('RELEASE_UPLOAD_URL', response.data.upload_url);
            } catch (error) {
              core.setFailed(error.message);
            }
