name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract version from PowerShell script
        id: extract_version
        shell: pwsh
        run: |
          $versionLine = Get-Content -Path create.ps1 | Select-String -Pattern '^# Version: (.+)$' | ForEach-Object { $_.Matches.Groups[1].Value.Trim() }
          Write-Host "Extracted version: $versionLine"
          echo $versionLine > RELEASE_TAG.txt

      - name: Set up output
        id: set_output
        run: echo "::set-output name=RELEASE_TAG::$(cat RELEASE_TAG.txt)"

  create_release:
    needs: release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: "Debug info"
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          echo "RELEASE_TAG: $RELEASE_TAG"

      - name: "Create release"
        run: |
          RELEASE_TAG=$(cat RELEASE_TAG.txt)
          echo "Creating release for tag: $RELEASE_TAG"
          git tag -a "$RELEASE_TAG" -m "Release $RELEASE_TAG"
          git push origin "$RELEASE_TAG"
