name: "Release"

on:
  push:
    branches:
      - main

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Determine tag"
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            RELEASE_TAG=$(echo "${GITHUB_REF#refs/tags/}" | sed 's/[^a-zA-Z0-9._-]/_/g')
            echo "RELEASE_TAG=${RELEASE_TAG}" >> $GITHUB_ENV
          else
            echo "Not a tag push. Skipping release step."
            exit 0
          fi

      - name: "Debug info"
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          echo "RELEASE_TAG: $RELEASE_TAG"

      - name: "Create release"
        uses: "actions/github-script@v6"
        with:
          github-token: "${{ secrets.GHTOKEN }}"
          script: |
            try {
              const response = await github.rest.repos.createRelease({
                draft: false,
                generate_release_notes: true,
                name: process.env.RELEASE_TAG,
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: process.env.RELEASE_TAG,
              });

              core.exportVariable('RELEASE_ID', response.data.id);
              core.exportVariable('RELEASE_UPLOAD_URL', response.data.upload_url);
            } catch (error) {
              core.setFailed(error.message);
            }
