name: Custom Release Workflow

on:
  push:
    branches:
      - main

jobs:
  run-custom-action:

    runs-on: ubuntu-latest

    steps:
      - name: Run HelloWorldAction
        id: helloworldaction
        uses: JeroenBL/HelloWorldAction@v0.1
        with:
          UserName: JeroenBL

      - name: Output message
        run: echo "${{ steps.helloworldaction.outputs.message }}"
