name: Custom Release Workflow

on:
  push:
    branches:
      - main

jobs:
  run-custom-action:

    runs-on: ubuntu-latest

    steps:
      - name: Run Custom Action
        id: helloworldaction
        uses: JeroenBL/HelloWorldAction@v0.1
        with:
          UserName: JeroenBL
