 demo:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - id: autorelease
       uses: JeroenBL/AutoRelease@v0.1
     - name: Create release
       run: echo "${{ steps.generatePassword.outputs.tag }}"
       shell: bash
