name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., v1.0.0). Leave blank to use the latest version from CHANGELOG.md.'
        required: false

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Determine Version
      id: determine_version
      run: |
        if [ -n "${{ github.event.inputs.version }}" ]; then
          VERSION="${{ github.event.inputs.version }}"
          echo "Using provided version: $VERSION"
        else
          if [ -f CHANGELOG.md ]; then
            # Extract the latest version heading from CHANGELOG.md
            VERSION=$(grep -oP '^## \[\K[^]]+' CHANGELOG.md | head -n 1)
            if [ -z "$VERSION" ]; then
              echo "No versions found in CHANGELOG.md."
              exit 1
            fi
            echo "Using latest version from CHANGELOG.md: $VERSION"
          else
            echo "CHANGELOG.md not found. Cannot determine version."
            exit 1
          fi
        fi
        echo "version=$VERSION" >> $GITHUB_ENV

    - name: Create GitHub Release with Auto-Generated Notes
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.version }}
        release_name: ${{ env.version }}
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
