name: Custom Release Workflow

on:
  push:
    branches:
      - main

jobs:
  run-custom-action:

    runs-on: ubuntu-latest

    steps:
      - name: Run AutoRelease
        id: autorelease
        uses: JeroenBL/AutoRelease@v0.2
        with:
          UserName: JeroenBL
          Repository: ReleaseTest
          GHToken: ${{ secrets.GH_TOKEN }} 

      - name: Output message
        run: echo "${{ steps.autorelease.outputs.message }}"
