name: Custom Release Workflow

on:
  push:
    branches:
      - main

jobs:
  run-custom-action:

    runs-on: ubuntu-latest

    steps:
      - uses: JeroenBL/HelloWorldAction@v0.1
      - id: helloworldaction
        with:
          UserName: JeroenBL
      - name: Run Custom Action
        run: echo "${{ steps.helloworldaction.outputs.password }}"
        shell: bash
